// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"
import HelloController from "./hello-controller"
import SearchFormController from "./search_form-controller"
import AdminController from "./admin-controller"

application.register("hello", HelloController)



application.register("search-form", SearchFormController)
application.register("admin", AdminController)
